version: '3.7'

volumes:

  datastream:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind

  compliance:
    driver: local
    driver_opts:
      type: none
      device: $PWD/compliance
      o: bind

services:

  stream_partition_1:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: covid19ingest_1
    environment: 
      - PARTITION_ID=1
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=covid19
    volumes:
      - datastream:/data
    restart: always

  stream_partition_2:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: covid19ingest_2
    environment: 
      - PARTITION_ID=2
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=covid19
    volumes:
      - datastream:/data
    restart: always

  stream_partition_3:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: covid19ingest_3
    environment: 
      - PARTITION_ID=3
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=covid19
    volumes:
      - datastream:/data
    restart: always

  stream_partition_4:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: covid19ingest_4
    environment: 
      - PARTITION_ID=4
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=covid19
    volumes:
      - datastream:/data
    restart: always

  compliance_partition_1:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_1
    environment: 
      - PARTITION_ID=1
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_2:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_2
    environment: 
      - PARTITION_ID=2
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_3:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_3
    environment: 
      - PARTITION_ID=3
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_4:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_4
    environment: 
      - PARTITION_ID=4
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_5:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_5
    environment: 
      - PARTITION_ID=5
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_6:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_6
    environment: 
      - PARTITION_ID=6
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_7:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_7
    environment: 
      - PARTITION_ID=7
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always

  compliance_partition_8:
    build:
      context: ./src/stream
      dockerfile: Dockerfile
    container_name: compliance_ingest_8
    environment: 
      - PARTITION_ID=8
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - STREAM_TYPE=compliance
    volumes:
      - compliance:/compliance
    restart: always
